### ISSUE TITLE
Do u mean print?

### ISSUE THREAD

**Issue by wolf-yuan-6115** [irasponsible/protonpass_json_to_bitwarden_csv#1]
https://github.com/irasponsible/protonpass_json_to_bitwarden_csv/blob/bd616c6a99d8841511afd9b8c69a0eb72d5679f6/protonpass_json_to_bitwarden_csv.py#L79

**Comment by irasponsible** [comment]
Nah, if it gets to the end and prints, then the console window closes straight after. Not an issue if you use -i or launch it through a terminal, but just in case it was run standalone, I finished on an input() so the user has to press enter to close.

**Comment by wolf-yuan-6115** [comment]
> Nah, if it gets to the end and prints, then the console window closes straight after. Not an issue if you use -i or launch it through a terminal, but just in case it was run standalone, I finished on an input() so the user has to press enter to close.

Oh, I ran the script without any arguments, it makes "a bit" sense now
